name: 'Deploy Pinafood using GH Actions to GH Pages'

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build Project
        run: yarn build

      - name: Upload production-ready file
        uses: actions/upload-artifact@v2
        with:
          name: production-file
          path: ./dist

  deploy:
    name: Deploy App
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Donwload production-ready file
        uses: actions/download-artifact@v2
        with:
          name: production-file
          path: ./dist

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
